name: Deploy to AWS
on:
    push:
        branches: testing

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '14'
            - name: Create .env file
              run: |
                touch .env
                echo VITE_MONGO_URL = 'mongodb+srv://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASS }}@roadstat.tnbn7xp.mongodb.net/?retryWrites=true&w=majority&appName=${{ secrets.MONGODB_NAME }}' >> .env
                echo VITE_API_URL = http://track.roadstat.com:3000/api >> .env
                echo VITE_GOOGLE_MAP_API=[api key] >> .env
                echo VITE_OPEN_WEATHER_API=[api key] >> .env
                cat .env
            - name: Build
              run: |
                npm install --legacy-peer-deps
            - uses: aws-actions/configure-aws-credentials@v4
              name: Configure aws credentials
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: 'us-east-1'
            - name: Login to AWS ECR
              run: |
                aws ecr create-repository --repository-name roadstat --endpoint-url https://api.ecr.us-east-1.vpce-0b686f2e7c060fd4f.amazonaws.com
            #     aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b1j6b3t7
            # - name: Build and Push Docker Image
            #   run: |  
            #     docker build -t roadstat-repo .
            #     docker tag roadstat-repo:latest public.ecr.aws/b1j6b3t7/roadstat-repo:latest
            #     docker push public.ecr.aws/b1j6b3t7/roadstat-repo:latest
            # - name: Deploy to AWS ECS
            #   run: |
            #     aws ecs update-service --cluster 'roadstat-cluster' --service 'roadstat' --force-new-deployment

