name: Deploy to AWS
on:
    push:
        branches: main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '14'
            - name: Create .env file
              run: |
                touch .env
                echo VITE_MONGO_URL = 'mongodb+srv://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASS }}@gokaddal.qicnveb.mongodb.net/?retryWrites=true&w=majority&appName=${{ secrets.MONGODB_NAME }}' >> .env
                echo VITE_API_URL = http://roadstat-1958f9dd23afe0b9.elb.us-east-1.amazonaws.com:3000/api >> .env
                echo VITE_GOOGLE_MAP_API=[api key] >> .env
                echo VITE_OPEN_WEATHER_API=${{ secrets.OPEN_WEATHER }} >> .env
                cat .env
            - name: Build
              run: |
                npm install --legacy-peer-deps
            - uses: aws-actions/configure-aws-credentials@v4
              name: Configure aws credentials
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: 'us-east-1'
            - name: Login to AWS ECR
              run: |
               aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 843257401278.dkr.ecr.us-east-1.amazonaws.com
            - name: Build Docker Image
              run: |  
                docker build -t roadstat .
            - name: Push Docker Image
              if: github.ref == 'refs/heads/main'
              run: |
                docker tag roadstat:latest 843257401278.dkr.ecr.us-east-1.amazonaws.com/roadstat:latest
                docker push 843257401278.dkr.ecr.us-east-1.amazonaws.com/roadstat:latest
            - name: Deploy to AWS ECS
              if: github.ref == 'refs/heads/main'
              run: |
                aws ecs update-service --cluster 'roadstat-cluster' --service 'roadstat-app-service' --force-new-deployment

