name: Deploy to AWS
on:
    push:
        branches: testing

jobs:
    deploy:
        runs-on: ubunut-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: 'us-east-1'
            - name: Login to AWS ECR
              run: |
                aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b1j6b3t7
            - name: Build and Push Docker Image
              run: |  
                docker build -t roadstat-repo .
                docker tag roadstat-repo:latest public.ecr.aws/b1j6b3t7/roadstat-repo:latest
                docker push public.ecr.aws/b1j6b3t7/roadstat-repo:latest

