name: Deploy to AWS
on:
    push:
        branches: main
    pull_request:

jobs:
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_A }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_A }}
                aws-region: 'ca-central-1'
            - name: Install AWS CLI
              run: |
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install
            - name: Login to AWS ECR
              run: |
                 aws ecr get-login-password --region ca-central-1 | docker login --username ${{ secrets.ECR_USER }} --password-stdin ${{ secrets.ECR_PASS }}
            - name: Build Docker Image
              run: |
                  docker build -t roadstat .
            - name: Push Docker Image
              if: github.ref == 'refs/heads/main'
              run: |
                  docker tag roadstat:latest ${{ secrets.ECR_PASS }}/${{ secrets.ECR_REPO }}:latest
                  docker push ${{ secrets.ECR_PASS }}/${{ secrets.ECR_REPO }}:latest
            - name: Deploy to AWS ECS
              if: github.ref == 'refs/heads/main'
              run: |
                  aws ecs update-service --cluster ${{ secrets.ROADSTAT_CLUSTER_NAME }} --service ${{ secrets.ROADSTAT_SERVICE_NAME }} --force-new-deployment
